### ISSUE TITLE
glyphicons-halflings license

### ISSUE THREAD

**Issue by mudrd8mz** [Steppe/moodle-mast#50]
As far as I know, the license of the glyphicons-halflings is not compatible with GPLv3. As such, they can't be distributed in a single package.

**Comment by GranatenArnold** [comment]
Hello David, thanks for pointing this out. I do have a question, though. On the bootstrap homepage, it says that the glyphicons are free to use ( "[...]Glyphicons Halflings are normally not available for free, but their creator has made them available for Bootstrap free of cost. As a thank you, we only ask that you include a link back to Glyphicons whenever possible." ).
http://getbootstrap.com/components/

We changed the glyphicons but I'm wondering if we really have to?

**Comment by mudrd8mz** [comment]
As I understand that statement, it applies only to Glyphicons that are distributed together with the bootstrap. Not that you can also use them under same conditions. For that reason, in my own code, I always use only those that ship together with the bootstrap in Moodle code.
Alternatively, maybe you can make your plugin use Glyphicons but have instructions for admins to install them themselves on their site (that is, not include and re-distribute then with your package).

**Comment by GranatenArnold** [comment]
Thanks for your insight and explanation as we are still strangers to the field of licensing and still learning more about it!
We have now solved this issue by only using icons that are being distributed with the Moodle core.
