### ISSUE TITLE
Language file error ?

### ISSUE THREAD

**Issue by stuartmealor** [Steppe/moodle-mast#58]
Interesting plugin!
I got some error messages on installation
"Invalid get_string() identifier: 'moodleanalyst' or component 'report_moodleanalyst'. Perhaps you are missing $string['moodleanalyst'] = ''; in /var/www/business/report/moodleanalyst/lang/en/report_moodleanalyst.php?

```
line 349 of /lib/classes/string_manager_standard.php: call to debugging()
line 6656 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
line 27 of /report/moodleanalyst/settings.php: call to get_string()
line 437 of /admin/settings/plugins.php: call to include()
line 6776 of /lib/adminlib.php: call to require()
line 532 of /admin/index.php: call to admin_get_root()"
```

Result is that Administration > Reports shows:
[[moodleanalyst]]
Note - I installed from .zip, extracted, and renamed moodle-analyst-master to moodleanalyst before triggering the installation.

**Comment by GranatenArnold** [comment]
Thanks, I will fix this right away!
A fresh installation is probably necessary to get the proper name displayed in the report block.
